### ISSUE TITLE
Проверить ДЗ

### ISSUE THREAD

**Issue by fadeciness** [fadeciness/fuel-consumption#1]

**Comment by fadeciness** [comment]
Указанные недостатки устранил, но есть ещё вопрос про юнит-тесты:
У меня в сервисе есть метод
```java
int calculate(double consumptionPerHundredKm, int fuelVolumeLiter)
```
Я написал три теста, описывающие следующие ситуации:
1. В баке нет топлива
2. В баке топлива меньше, чем расход на сто километров
3. В баке топлива больше, чем расход на сто километров

Насколько грамотно я проверяю ситуации в тестах? Достаточно этих тестов? Нужно ли проверять граничные значения самих типов данных в этой ситуации?

**Comment by coursar** [comment]
Нет, мы пока это опускаем.

Вам достаточно работать в режиме, когда вы считаете, что находитесь в границах типов.

А там уже будет зависеть от того, что скажут на работе.
